projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: ugf7wwjncbgb7k53op7jahas54
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
